/*******************************************************************************
 * Jan Kožusznik
 * Copyright (c) 2016 All Right Reserved, http://www.kozusznik.cz
 *
 * This file is subject to the terms and conditions defined in
 * file 'LICENSE.txt', which is part of this source code package.
 ******************************************************************************/
package pj1.zt02;

import java.util.Arrays;
import java.util.Collection;

/**
 * @author Jan Kožusznik
 * @version 0.1
 */
public class PevnyBalikSlov extends BalikSlov {

  private String[] words;

  /**
   *
   */
  public PevnyBalikSlov() {
    words = new String[]{"Ernest", "Hemingway", "Stařec", "a", "moře", "Byl",
        "už", "starý", "vyjížděl", "sám", "v", "loďce", "na", "lov", "do",
        "Golfského", "proudu", "a", "teď", "tomu", "bylo", "čtyřiaosmdesát",
        "dní", "co", "nechytil", "jedinou", "rybu", "Prvních", "čtyřicet",
        "dní", "s", "ním", "jezdil", "chlapec", "Ale", "po", "čtyřiceti",
        "dnech", "bez", "úlovku", "řekli", "chlapci", "jeho", "rodiče", "že",
        "starý", "je", "už", "dočista", "a", "nadobro", "salao", "což", "je",
        "nejhorší", "druh", "smolaře", "a", "chlapec", "začal", "na", "jejich",
        "příkaz", "jezdit", "s", "jiným", "člunem", "který", "ulovil", "tři",
        "pořádné", "ryby", "hned", "první", "týden", "Chlapec", "byl", "smutný",
        "když", "viděl", "jak", "se", "starý", "každý", "den", "vrací", "s",
        "prázdnou", "loďkou", "a", "vždycky", "mu", "šel", "pomoci", "odnést",
        "buď", "kotouče", "šňůry", "nebo", "hák", "s", "bodcem", "a", "harpunu",
        "a", "plachtu", "skasanou", "kolem", "stěžně", "Plachta", "byla",
        "záplatována", "pytli", "od", "mouky", "a", "svinuta", "vyhlížela",
        "jako", "vlajka", "trvalé", "porážky", "Stařec", "byl", "hubený",
        "vyzáblý", "a", "zátylek", "měl", "zrytý", "hlubokými", "rýhami", "Na",
        "lících", "mu", "vyvstaly", "hnědé", "skvrny", "kůže", "zrohovatělé",
        "na", "ochranu", "před", "odrazem", "slunce", "v", "tropickém", "moři",
        "Ty", "skvrny", "mu", "sahaly", "po", "stranách", "obličeje", "až",
        "dolů", "a", "ruce", "měl", "zjizvené", "hlubokými", "zářezy", "od",
        "toho", "jak", "se", "lopotil", "s", "těžkými", "rybami", "na",
        "šňůrách", "Žádná", "z", "těch", "jizev", "však", "nebyla", "čerstvá",
        "Byly", "tak", "staré", "jako", "výmoly", "v", "bezrybé", "poušti",
        "Všechno", "na", "něm", "bylo", "staré", "až", "na", "jeho", "oči",
        "Ty", "měly", "stejnou", "barvu", "jako", "moře", "a", "hleděly",
        "vesele", "a", "nezkrušeně", "Santiago", "řekl", "mu", "chlapec",
        "když", "šplhali", "na", "břeh", "kam", "pak", "vytahovali", "loďku",
        "Mohl", "bych", "jezdit", "zase", "s", "vámi", "Vydělali", "jsme",
        "nějaké", "peníze", "Stařec", "kdysi", "naučil", "chlapce", "rybařit",
        "a", "chlapec", "ho", "miloval", "Ne", "odpověděl", "stařec", "Jsi",
        "na", "šťastném", "člunu", "Zůstaň", "s", "nimi", "Ale", "vzpomeňte",
        "si", "jak", "jste", "jednou", "nezavadil", "o", "rybu",
        "sedmaosmdesát", "dní", "a", "pak", "jsme", "tři", "neděle", "chytali",
        "kapitální", "kusy", "den", "co", "den", "Vzpomínám", "přisvědčil",
        "stařec", "Já", "vím", "že", "jsi", "ode", "mne", "neodešel", "proto",
        "že", "bys", "pochyboval", "To", "mi", "poručil", "táta", "Jsem",
        "ještě", "kluk", "a", "musím", "ho", "poslouchat", "Já", "vím",
        "odpověděl", "stařec", "To", "je", "docela", "přirozené", "Nemá",
        "zrovna", "moc", "víry", "Nemá", "řekl", "stařec", "Ale", "my", "máme",
        "Vid", "Máme", "potvrdil", "chlapec", "Můžu", "vás", "pozvat", "na",
        "Terasu", "na", "pivo", "Pak", "odneseme", "věci", "domů", "Proč", "ne",
        "souhlasil", "stařec", "Jako", "rybář", "rybáře", "Seděli", "na",
        "Terase", "a", "mnoho", "rybářů", "si", "dělalo", "ze", "starce",
        "legraci", "a", "on", "se", "nezlobil", "Jiní", "z", "těch", "starších",
        "se", "na", "něho", "dívali", "a", "bylo", "jim", "smutno", "Ale",
        "nedávali", "to", "najevo", "a", "hovořili", "zdvořile", "o", "proudu",
        "o", "tom", "v", "jaké", "hloubce", "za", "sebou", "dnes", "vláčeli",
        "šňůry", "o", "stále", "pěkném", "počasí", "a", "o", "tom", "co",
        "viděli", "Rybáři", "kteří", "měli", "toho", "dne", "štěstí", "byli",
        "už", "zpátky", "vyvrhli", "své", "martiny", "a", "odnesli", "je",
        "naložené", "v", "celé", "délce", "napříč", "přes", "dvě", "prkna",
        "klopýtajíce", "dva", "a", "dva", "na", "koncích", "obou", "prken",
        "do", "rybárny", "kde", "čekali", "na", "nákladní", "auto", "s",
        "ledem", "aby", "je", "odvezlo", "na", "trh", "do", "Havany", "Ti",
        "kdo", "chytili", "žraloky", "dopravili", "je", "do", "továrny", "na",
        "jejich", "zpracování", "naproti", "přes", "zátoku", "kde", "je",
        "vyzdvihli", "na", "kladkostrojích", "vyřízli", "jim", "játra",
        "odřezali", "ploutve", "stáhli", "kůži", "a", "jejich", "maso",
        "rozkrájeli", "na", "pruhy", "k", "nasolení", "Když", "vál", "vítr",
        "z", "východu", "přinášel", "přes", "přístavní", "zátoku", "zápach",
        "žraloci", "továrny", "ale", "dnes", "bylo", "cítit", "jen",
        "slabounké", "závany", "protože", "se", "vítr", "stočil", "k", "jihu",
        "a", "pak", "utichl", "a", "na", "Terase", "bylo", "příjemně", "a",
        "slunečno", "Santiago", "ozval", "se", "chlapec", "Copak", "odpověděl",
        "stařec", "Držel", "v", "ruce", "sklenici", "a", "myslel", "na", "dobu",
        "před", "mnoha", "lety", "Můžu", "vám", "jet", "opatřit", "na", "zítra",
        "sardinky", "Ne", "Běž", "si", "zahrát", "baseball", "Veslovat",
        "ještě", "dokážu", "a", "Rogelio", "rozhodí", "síť", "Jel", "bych",
        "rád", "Když", "s", "vámi", "nemůžu", "lovit", "chtěl", "bych", "vám",
        "aspoň", "nějak", "po", "sloužit", "Pozval", "jsi", "mě", "na", "pivo",
        "řekl", "mu", "stařec", "Jsi", "už", "hotový", "mužský", "Kolik", "mi",
        "bylo", "když", "jste", "mě", "po", "prvé", "vzal", "do", "člunu",
        "Pět", "a", "málem", "jsi", "přišel", "o", "život", "když", "jsem",
        "vytáhl", "rybu", "ještě", "moc", "živou", "a", "ona", "nám", "málem",
        "rozmlátila", "člun", "na", "maděru", "Pamatuješ", "Pamatuju", "se",
        "jak", "plácala", "a", "tloukla", "ocasem", "a", "jak", "praskla",
        "lavička", "u", "vesel", "a", "na", "ty", "rány", "když", "jste", "do",
        "ní", "bušil", "Pamatuju", "se", "jak", "jste", "mě", "hodil", "na",
        "příď", "na", "stočené", "mokré", "šňůry", "jak", "se", "celý", "člun",
        "třásl", "a", "na", "ty", "rány", "když", "jste", "do", "ní", "bušil",
        "jako", "když", "se", "poráží", "strom", "a", "jak", "jsem", "byl",
        "celý", "od", "krve", "která", "tak", "sladce", "páchla", "Opravdu",
        "si", "to", "pamatuješ", "nebo", "jsem", "ti", "to", "jenom",
        "vyprávěl", "Pamatuju", "si", "všechno", "od", "té", "doby", "co",
        "jsme", "spolu", "byli", "po", "prvé", "Stařec", "se", "na", "něho",
        "podíval", "očima", "zanícenýma", "od", "slunce", "důvěřivýma", "a",
        "láskyplnýma", "Kdybys", "byl", "můj", "vzal", "bych", "tě", "s",
        "sebou", "a", "vsadil", "bych", "všechno", "na", "jednu", "kartu",
        "řekl", "mu", "Ale", "jsi", "tátův", "a", "mámin", "a", "jezdíš", "se",
        "šťastným", "člunem", "Smím", "sehnat", "ty", "sardinky", "Vím", "taky",
        "kde", "opatřit", "čtyři", "návnady", "Mně", "zbyly", "ještě", "dnešní",
        "Dal", "jsem", "je", "do", "bedničky", "se", "solí", "Nechtě", "mě",
        "seženu", "vám", "čtyři", "čerstvé", "Jednu", "namítl", "stařec",
        "Nikdy", "neztratil", "naději", "a", "víru", "Teď", "však", "v", "něm",
        "ožívaly", "jako", "když", "se", "zvedá", "svěží", "vánek", "Dvě",
        "smlouval", "chlapec", "Tak", "dvě", "souhlasil", "stařec", "Ale",
        "neukradl", "jsi", "je", "Ukradl", "bych", "je", "přiznal", "chlapec",
        "Ale", "tyhle", "jsem", "koupil", "Děkuji", "ti", "řekl", "mu",
        "stařec", "Byl", "příliš", "prostý", "na", "to", "aby", "uvažoval",
        "kdy", "dospěl", "k", "pokoře", "Ale", "věděl", "že", "k", "ní",
        "dospěl", "a", "věděl", "že", "pokora", "není", "člověku", "k", "necti",
        "a", "není", "na", "újmu", "opravdové", "hrdosti", "Při", "tomhle",
        "proudu", "to", "zítra", "půjde", "dobře", "poznamenal", "Kam",
        "pojedete", "zeptal", "se", "ho", "chlapec", "Daleko", "do", "moře",
        "abych", "se", "vrátil", "až", "se", "změní", "vítr", "Chci", "vyrazit",
        "před", "svítáním", "Pokusím", "se", "ho", "přimět", "aby", "vyplul",
        "taky", "dál", "řekl", "chlapec", "To", "bychom", "vám", "mohli",
        "přijít", "na", "pomoc", "kdyby", "vám", "zabralo", "něco", "opravdu",
        "velikého", "Ten", "loví", "nerad", "moc", "daleko", "od", "břehu",
        "To", "je", "pravda", "připustil", "chlapec", "Ale", "já", "jako",
        "uvidím", "něco", "kam", "on", "nedohlídne", "třeba", "nějakého",
        "ptáka", "na", "číhané", "a", "přiměju", "ho", "aby", "vyplul", "dál",
        "chytit", "nějakou", "dorádu", "To", "má", "tak", "špatné", "oči", "Je",
        "skoro", "slepý", "To", "je", "divné", "zamyslel", "se", "stařec",
        "Nikdy", "nelovil", "želvy", "To", "je", "na", "oči", "mor", "Ale",
        "vy", "jste", "u", "Moskytího", "pobřeží", "lovil", "želvy", "celá",
        "léta", "a", "máte", "oči", "dobré", "Já", "jsem", "vůbec", "divný",
        "staroch", "Ale", "jste", "teď", "dost", "silný", "na", "opravdu",
        "velkou", "rybu", "Myslím", "že", "jsem", "A", "pak", "znám", "spoustu",
        "triků", "Odneseme", "věci", "domů", "řekl", "chlapec", "Abych", "mohl",
        "vzít", "síť", "a", "vypravit", "se", "na", "ty", "sardinku", "Sebrali",
        "z", "člunu", "výstroj", "Stařec", "nesl", "přes", "rameno", "stěžeň",
        "a", "chlapec", "nesl", "bednu", "se", "stočenými", "tvrdými",
        "pletenci", "hnědých", "šňůr", "bodec", "s", "hákem", "a", "harpunu",
        "s", "násadou", "Bednička", "s", "návnadou", "ležela", "na", "zádi",
        "loďky", "vedle", "kyje", "jehož", "se", "užívalo", "ke", "zdolání",
        "velkých", "ryb", "když", "byly", "přitaženy", "po", "bok", "člunu",
        "Nikdo", "by", "byl", "starému", "nic", "neukradl", "ale", "bylo",
        "lépe", "vzít", "plachtu", "a", "tlusté", "šňůry", "domů", "protože",
        "jim", "škodila", "rosa", "a", "protože", "i", "když", "by", "mu",
        "místní", "lidé", "docela", "jistě", "nic", "neukradli", "stařec",
        "měl", "za", "to", "že", "bodec", "a", "harpuna", "ponechané", "ve",
        "člunu", "by", "jen", "zbytečně", "někoho", "pokoušely", "Kráčeli",
        "spolu", "po", "silnici", "k", "starcově", "chatrči", "a", "vešli",
        "otevřenými", "dveřmi", "Starý", "opřel", "stěžeň", "se", "svinutou",
        "plachtou", "o", "stěnu", "a", "chlapec", "složil", "bednu", "a",
        "ostatní", "nářadí", "vedle", "na", "zem", "Stěžeň", "byl", "skoro",
        "tak", "dlouhý", "jako", "jediná", "jizba", "v", "chatrči", "Chatrč",
        "byla", "postavena", "z", "tuhých", "listenů", "jež", "chrání",
        "pupeny", "královské", "palmy", "a", "kterým", "se", "říká", "guano",
        "a", "byla", "v", "ní", "postel", "stůl", "jedna", "židle", "a",
        "ohniště", "na", "hlinité", "podlaze", "kde", "se", "vařilo", "na",
        "dřevěném", "uhlí", "Na", "hnědých", "stěnách", "z", "překrývajících",
        "se", "listů", "houževnatě", "vláknitého", "guana", "visel",
        "barvotiskNejsvětějšího", "srdce", "Ježíšova", "a", "ještě", "jeden",
        "obrázek", "Panenky", "Marie", "Cobreské", "To", "byly", "památky",
        "po", "jeho", "ženě", "Kdysi", "na", "stěně", "visívala", "její",
        "tónovaná", "fotografie", "ale", "sundal", "ji", "protože", "si", "při",
        "pohledu", "na", "ni", "připadal", "příliš", "osamělý", "a", "teď",
        "ležela", "na", "polici", "v", "koutě", "pod", "jeho", "čistou",
        "košilí", "Co", "máte", "k", "jídlu", "zeptal", "se", "chlapec",
        "Hrnec", "žluté", "rýže", "s", "rybou", "Chceš", "trochu", "Ne",
        "Najím", "se", "doma", "Mám", "vám", "rozdělat", "oheň", "Ne",
        "Rozdělám", "si", "ho", "později", "Nebo", "tu", "rýži", "sním",
        "studenou", "Smím", "si", "vzít", "síť", "Samozřejmě", "Ve",
        "skutečnosti", "tu", "žádná", "síť", "nebyla", "a", "chlapec", "si",
        "pamatoval", "kdy", "ji", "prodali", "Ale", "hráli", "tuhle",
        "smyšlenou", "hru", "každý", "den", "Neexistoval", "ani", "hrnec",
        "žluté", "rýže", "s", "rybou", "a", "to", "chlapec", "věděl", "taky",
        "Pětaosmdesát", "je", "šťastné", "číslo", "řekl", "stařec", "Co", "bys",
        "tak", "říkal", "tomu", "kdybych", "se", "vrátil", "s", "kusem",
        "který", "by", "vydal", "přes", "tři", "metráky", "Vezmu", "si", "síť",
        "a", "půjdu", "na", "sardinky", "Sednete", "si", "na", "slunce", "na",
        "zápraží", "Sednu", "Mám", "tu", "včerejší", "noviny", "a", "přečtu",
        "si", "jak", "dopadl", "baseball", "Chlapec", "nevěděl", "jestli", "ty",
        "včerejší", "noviny", "nejsou", "taky", "smyšlené", "Ale", "stařec",
        "je", "vytáhl", "zpod", "postele", "Perico", "mi", "je", "dal", "v",
        "hospodě", "vysvětlil", "chlapci", "Vrátím", "se", "až", "seženu",
        "sardinky", "Nechám", "vaše", "se", "svými", "u", "ledu", "a", "ráno",
        "se", "o", "ně", "můžeme", "rozdělit", "Povíte", "mi", "pak", "o",
        "baseballu", "až", "se", "vrátím", "Yankeeové", "nemůžou", "prohrát",
        "Jenže", "já", "mám", "strach", "z", "clevelandských", "Indiánů", "Věř",
        "na", "Yankeee", "synku", "Mají", "přece", "v", "mužstvu", "slavného",
        "DiMaggia", "Mám", "strach", "z", "detroitských", "Tygrů", "a", "z",
        "clevelandských", "Indiánů", "Dej", "si", "pozor", "nebo", "se",
        "začneš", "bát", "i", "Rudochů", "z", "Cincinnati", "nebo",
        "Běloponožkářůz", "Chicaga", "Vy", "to", "už", "prostudujete", "a",
        "řeknete", "mi", "až", "se", "vrátím", "Neměli", "bychom", "si", "na",
        "pětaosmdesátku", "vsadit", "do", "posledního", "kola", "loterie",
        "Zítra", "to", "bude", "pětaosmdesát", "dní", "To", "bychom", "mohli",
        "odpověděl", "chlapec", "Ale", "co", "spíš", "na", "sedmaosmdesátku",
        "To", "byl", "váš", "největší", "rekord", "Dvakrát", "se", "to",
        "nestane", "Myslíš", "že", "seženeš", "nějakou", "pětaosmdesátku",
        "Můžu", "si", "ji", "zamluvit", "Jeden", "aršík", "To", "je", "dva",
        "a", "půl", "dolaru", "Od", "koho", "bychom", "si", "to", "vypůjčili",
        "To", "nic", "není", "Dva", "a", "půl", "dolaru", "si", "vždycky",
        "někde", "vypůjčím", "Myslím", "že", "bych", "to", "taky", "dokázal",
        "Ale", "nepokouším", "se", "o", "to", "Člověk", "si", "začne",
        "půjčovat", "a", "skončí", "žebrotou", "Držte", "se", "v", "teple",
        "dědo", "řekl", "chlapec", "Pamatujte", "že", "máme", "září", "Měsíc",
        "kdy", "táhnou", "velké", "ryby", "odpověděl", "stařec", "V", "máji",
        "dokáže", "rybařit", "každý", "Půjdu", "na", "ty", "sardinky", "řekl",
        "chlapec", "Když", "se", "chlapec", "vrátil", "stařec", "spal", "na",
        "židli", "a", "slunce", "už", "zapadlo", "Chlapec", "stáhl", "s",
        "postele", "starou", "vojenskou", "pokrývku", "a", "přehodil", "ji",
        "přes", "opěradlo", "židle", "a", "starci", "přes", "ramena", "Byla",
        "to", "zvláštní", "ramena", "dosud", "mocná", "třebaže", "velice",
        "stará", "I", "jeho", "šíje", "byla", "dosud", "statná", "a", "rýhy",
        "nebyly", "tak", "vidět", "když", "stařec", "spal", "a", "hlava", "mu",
        "padala", "dopředu", "Košili", "měl", "tolikrát", "záplatovanou", "že",
        "byla", "jako", "jeho", "plachta", "a", "záplaty", "vyrudly", "sluncem",
        "do", "mnoha", "různých", "odstínů", "Starcova", "hlava", "však",
        "byla", "velice", "stará", "a", "když", "měl", "zavřené", "oči", "byla",
        "jeho", "tvář", "bez", "života", "Noviny", "mu", "ležely", "na",
        "kolenou", "a", "tíha", "jeho", "paže", "je", "tam", "přidržovala",
        "ve", "večerním", "větříku", "Byl", "bos", "Chlapec", "ho", "tak",
        "nechal", "a", "když", "přišel", "znovu", "stařec", "spal", "ještě",
        "Probuďte", "se", "dědo", "promluvil", "na", "něho", "chlapec", "a",
        "položil", "mu", "ruku", "na", "koleno", "Stařec", "otevřel", "oči",
        "a", "chvíli", "se", "vracel", "z", "nějaké", "daleké", "dálné",
        "cesty", "Pak", "se", "usmál", "Co", "je", "zeptal", "se", "Večeře",
        "oznámil", "chlapec", "Navečeříme", "se", "Nemám", "zrovna", "hlad",
        "Pojďte", "a", "najezte", "se", "To", "nejde", "rybařit", "a", "nejíst",
        "Dělávám", "to", "řekl", "stařec", "vstávaje", "sebral", "noviny", "a",
        "složil", "je", "Pak", "začal", "skládat", "pokrývku", "Nechtě", "si",
        "tu", "pokrývku", "kolem", "sebe", "napomenul", "ho", "chlapec",
        "Nebudete", "rybařit", "bez", "jídla", "co", "já", "budu", "živ", "Tak",
        "žij", "hodně", "dlouho", "a", "dávej", "na", "sebe", "pozor",
        "odpověděl", "mu", "stařec", "Co", "budeme", "jíst", "Černé", "fazole",
        "s", "rýží", "pečené", "banány", "a", "trochu", "dušeného", "masa",
        "Chlapec", "přinesl", "večeři", "v", "kovovém", "šálku", "o", "dvou",
        "miskách", "z", "Terasy", "Dva", "příbory", "nože", "a", "vidličky",
        "a", "lžíce", "měl", "v", "kapse", "každý", "příbor", "zabalená", "do",
        "papírového", "ubrousku", "Kdo", "ti", "to", "dal", "Martin",
        "Hostinský", "Musím", "mu", "poděkovat", "Už", "jsem", "mu",
        "poděkoval", "řekl", "chlapec", "Vy", "už", "mu", "děkovat", "nemusíte",
        "Dám", "mu", "maso", "z", "břicha", "příští", "velké", "ryby",
        "prohlásil", "stařec", "Udělal", "tohle", "pro", "nás", "už", "častěji",
        "Tak", "se", "mi", "zdá", "To", "mu", "musím", "dát", "něco", "víc",
        "než", "maso", "z", "břicha", "Je", "od", "něho", "moc", "hezké", "že",
        "tak", "na", "nás", "myslí", "Posílá", "dvě", "piva", "Já", "mám",
        "nejradši", "pivo", "v", "plechovkách", "Já", "vím", "Ale", "tohle",
        "je", "lahvové", "Odnesu", "mu", "pak", "láhve", "zpátky", "To", "jsi",
        "hodný", "řekl", "stařec", "Dáme", "se", "do", "jídla", "O", "to",
        "vám", "právě", "říkám", "odpověděl", "mu", "chlapec", "jemně",
        "Nechtěl", "jsem", "ty", "misky", "otvírat", "dokud", "nebudete",
        "hotov", "Už", "jsem", "pospíšil", "si", "stařec", "Potřeboval", "jsem",
        "jen", "chvilku", "na", "umytí", "Kde", "se", "umyl", "pomyslel", "si",
        "chlapec", "Pumpa", "byla", "ve", "vesnici", "o", "dvě", "ulice", "dál",
        "dolů", "po", "silnici", "Musím", "tu", "pro", "něho", "mít", "vodu",
        "umiňoval", "si", "chlapec", "v", "duchu", "a", "mýdlo", "a", "pořádný",
        "ručník", "Proč", "na", "nic", "nemyslím", "Musím", "mu", "opatřit",
        "ještě", "jednu", "košili", "a", "kazajku", "na", "zimu", "a", "nějaké",
        "boty", "a", "ještě", "jednu", "pokrývku", "To", "dušené", "maso", "je",
        "výborné", "pochválil", "ho", "stařec", "Povězte", "mi", "jak", "to",
        "vypadá", "s", "baseballem", "požádal", "chlapec", "V", "Americké",
        "lize", "není", "nad", "Yankeeje", "jak", "jsem", "říkal", "odpověděl",
        "stařec", "blaženě", "Dneska", "prohráli", "namítl", "mu", "chlapec",
        "To", "nic", "neznamená", "Slavný", "DiMaggio", "se", "zase", "našel",
        "Mají", "v", "mužstvu", "taky", "jiné", "hráče", "Samozřejmě", "Ale",
        "na", "něm", "nejvíc", "záleží", "Ve", "druhé", "lize", "mezi",
        "Brooklynem", "a", "Filadelfií", "musím", "sázet", "na", "Brooklyn",
        "Ale", "pak", "si", "zase", "vzpomenu", "na", "Dicka", "Sislera", "a",
        "na", "ty", "jeho", "ohromné", "drajvy", "ve", "starém", "parku", "To",
        "ještě", "nikdo", "jiný", "nedokázal", "Napaloval", "míč", "nejdál",
        "jak", "jsem", "kdy", "viděl", "Pamatuješ", "se", "jak", "chodíval",
        "na", "Terasu", "Chtěl", "jsem", "ho", "vzít", "na", "ryby", "ale",
        "styděl", "jsem", "se", "mu", "říct", "Tak", "jsem", "ti", "říkal",
        "abys", "mu", "řekl", "ty", "a", "ty", "jsi", "se", "styděl", "taky",
        "Já", "vím", "To", "byla", "velká", "chyba", "Byl", "by", "možná", "s",
        "námi", "jel", "A", "my", "bychom", "pak", "měli", "vzpomínku", "na",
        "celý", "život", "Rád", "bych", "vzal", "na", "ryby", "slavného",
        "DiMaggia", "zamyslel", "se", "stařec", "Jeho", "táta", "prý", "byl",
        "rybář", "Možná", "že", "byl", "tak", "chudý", "jako", "my", "a", "že",
        "by", "nám", "rozuměl", "Táta", "slavného", "Sislera", "nikdy", "nebyl",
        "chudý", "a", "hrál", "v", "první", "lize", "když", "byl", "tak",
        "starý", "jako", "já", "Když", "jsem", "já", "byl", "tak", "starý",
        "jako", "ty", "sloužil", "jsem", "jako", "námořník", "na",
        "plachetnici", "co", "plula", "do", "Afriky", "a", "viděl", "jsem",
        "večer", "na", "pobřeží", "lvy", "Já", "vím", "To", "jste", "mi",
        "vyprávěl", "Chceš", "si", "povídat", "o", "Africe", "nebo", "o",
        "baseballu", "Radši", "o", "baseballu", "odpověděl", "chlapec",
        "Povězte", "mi", "o", "slavném", "Johnovi", "J", "McGrawovi",
        "Vyslovil", "J", "po", "Španělsku", "jako", "cín", "Chodíval", "kdysi",
        "taky", "občas", "na", "Terasu", "Ale", "když", "se", "napil", "byl",
        "hrubý", "mluvil", "sprostě", "a", "nedalo", "se", "s", "ním", "vyjít",
        "Měl", "v", "hlavě", "vedle", "baseballu", "ještě", "koně", "Nosil",
        "aspoň", "pořád", "po", "kapsách", "dostihové", "seznamy", "a", "často",
        "říkával", "jména", "koní", "do", "telefonu", "Byl", "to", "slavný",
        "manažér", "přidal", "se", "chlapec", "Můj", "táta", "myslí", "že",
        "ten", "něj", "slavnější", "To", "proto", "že", "sem", "tak", "často",
        "jezdil", "namítl", "stařec", "Kdyby", "sem", "byl", "nepřestal",
        "jezdit", "každý", "rok", "Durocher", "myslel", "by", "si", "tvůj",
        "táta", "že", "nejslavnější", "manažér", "je", "on", "Ale", "kdo", "je",
        "opravdu", "nejslavnější", "manažér", "Luque", "nebo", "Mike",
        "Gonzalez", "Já", "myslím", "že", "jsou", "tak", "stejní", "A",
        "nejlepší", "rybář", "jste", "vy", "Ba", "ne", "Znám", "lepší", "Qué",
        "va", "odporoval", "chlapec", "Je", "hodně", "dobrých", "rybářů", "a",
        "pár", "jich", "je", "ohromných", "Ale", "vy", "jste", "jen", "jeden",
        "Děkuju", "ti", "To", "mi", "dělá", "dobře", "Jen", "doufám", "že",
        "se", "nenajde", "tak", "ohromná", "ryba", "aby", "nás", "usvědčila",
        "z", "nepravdy", "Taková", "ryba", "není", "jestli", "máte", "pořád",
        "ještě", "dost", "síly", "jak", "říkáte", "Možná", "že", "nejsem",
        "tak", "silný", "jak", "si", "myslím", "uvažoval", "stařec", "Ale",
        "znám", "spoustu", "všelijakých", "triků", "a", "mám", "pevnou", "vůli",
        "Měl", "byste", "si", "teď", "jít", "lehnout", "abyste", "byl", "ráno",
        "svěží", "Odnesu", "nádobí", "zpátky", "na", "Terasu", "Tak", "dobrou",
        "noc", "Ráno", "tě", "vzbudím", "Vy", "jste", "můj", "budíček", "řekl",
        "mu", "chlapec", "Stáří", "je", "můj", "budíček", "odpověděl", "mu",
        "stařec", "Proč", "se", "staří", "lidé", "probouzejí", "tak", "brzy",
        "Proto", "aby", "si", "prodloužili", "další", "den", "života", "To",
        "nevím", "poznamenal", "chlapec", "Vím", "jen", "že", "mladí",
        "chlapci", "spí", "dlouho", "a", "tvrdě", "Nezapomenu", "na", "to",
        "uklidnil", "ho", "stařec", "Vzbudím", "tě", "včas", "Nemám", "rád",
        "když", "mě", "budí", "on", "Připadám", "si", "jako", "bych", "byl",
        "malé", "dítě", "Já", "vím", "Vyspěte", "se", "dobře", "dědo",
        "Chlapec", "odešel", "Najedli", "se", "před", "chvílí", "u", "stolu",
        "beze", "světla", "a", "stařec", "si", "potmě", "svlekl", "kalhoty",
        "a", "vlezl", "si", "do", "postele", "Stočil", "si", "kalhoty", "aby",
        "si", "z", "nich", "udělal", "polštář", "a", "dovnitř", "nastrkal",
        "noviny", "Zavinul", "se", "do", "pokrývky", "a", "spal", "na",
        "jiných", "starých", "novinách", "nastlaných", "přes", "péra",
        "postele", "Usnul", "ve", "chvilce", "a", "zdálo", "se", "mu", "o",
        "Africe", "kde", "byl", "jako", "chlapec", "o", "dlouhých", "zlatých",
        "pobřežích", "a", "o", "bílých", "pobřežích", "tak", "bílých", "až",
        "z", "nich", "bolely", "oči", "o", "vysokých", "mysech", "a",
        "mohutných", "hnědých", "horách", "Plavil", "se", "teď", "podél",
        "těch", "břehů", "každou", "noc", "a", "slyšel", "ve", "snách", "řev",
        "příboje", "a", "viděl", "jak", "se", "tím", "příbojem", "blíží",
        "čluny", "domorodců", "Cítil", "ve", "spánku", "dehet", "a", "koudel",
        "ve", "spárách", "paluby", "a", "cítil", "vůně", "Afriky", "které", "z",
        "jitra", "přinášel", "větřík", "z", "pevniny", "Když", "ucítil",
        "větřík", "z", "pevniny", "probouzel", "se", "zpravidla", "a",
        "oblékal", "se", "aby", "šel", "vzbudit", "chlapce", "Ale", "dnes",
        "přišla", "vůně", "větříku", "z", "pevniny", "velice", "záhy", "a",
        "stařec", "věděl", "že", "je", "ještě", "příliš", "brzy", "v", "jeho",
        "snu", "a", "pokračoval", "v", "snění", "aby", "uviděl", "jak", "se",
        "bílé", "vrcholky", "Ostrovů", "vynořují", "z", "moře", "a", "pak",
        "snil", "o", "různých", "přístavištích", "a", "kotvištích", "na",
        "Kanárském", "souostroví", "Už", "se", "mu", "nezdávalo", "o",
        "bouřích", "ani", "o", "ženách", "ani", "o", "významných", "událostech",
        "ani", "o", "velikých", "rybách", "ani", "o", "zápasech", "ani", "o",
        "siláckých", "soutěžích", "ani", "o", "vlastní", "ženě", "Zdálo", "se",
        "mu", "teď", "jenom", "o", "různých", "místech", "a", "o", "lvech",
        "na", "pobřeží", "Hráli", "si", "v", "soumraku", "jako", "koťata", "a",
        "on", "je", "miloval", "právě", "tak", "jako", "miloval", "chlapce",
        "O", "chlapci", "se", "mu", "nezdálo", "nikdy", "Probral", "se",
        "jakoby", "nic", "podíval", "se", "otevřenými", "dveřmi", "na", "měsíc",
        "rozbalil", "si", "kalhoty", "a", "oblekl", "si", "je", "Za", "chatrčí",
        "se", "vymočil", "a", "pak", "vykročil", "po", "silnici", "aby",
        "vzbudil", "chlapce", "Třásl", "se", "jitřním", "chladem", "Ale",
        "věděl", "že", "se", "tou", "třasavkou", "zahřeje", "a", "že",
        "zanedlouho", "bude", "veslovat", "Dveře", "domku", "kde", "bydlel",
        "chlapec", "nebyly", "zamčeny", "Stařec", "je", "otevřel", "a", "vešel",
        "potichu", "bosýma", "nohama", "dovnitř", "Chlapec", "spal", "na",
        "kavalci", "v", "první", "místnosti", "a", "stařec", "ho", "jasně",
        "rozeznal", "ve", "světle", "blednoucího", "měsíce", "Uchopil", "ho",
        "jemně", "za", "jednu", "nohu", "a", "držel", "ho", "dokud", "chlapec",
        "neprocitl", "neotočil", "se", "a", "nepohlédl", "na", "něho", "Stařec",
        "přikývl", "a", "chlapec", "si", "vzal", "kalhoty", "se", "židle",
        "vedle", "lůžka", "a", "natáhl", "si", "je", "vsedě", "na", "kavalci",
        "Stařec", "vyšel", "ze", "dveří", "a", "chlapec", "ho", "následoval",
        "Byl", "ospalý", "a", "stařec", "ho", "objal", "paži", "kolem",
        "ramenou", "a", "řekl", "mu", "Odpusť", "Qué", "va", "odpověděl",
        "chlapec", "To", "přece", "člověk", "musí", "Šli", "po", "silnici", "k",
        "starcově", "chatrči", "a", "po", "celou", "cestu", "je", "míjeli",
        "ve", "tmě", "bosí", "muži", "kteří", "nesli", "stěžně", "svých",
        "člunů", "Když", "došli", "k", "chatrči", "chlapec", "vzal", "kotouče",
        "šňůry", "v", "košíku", "a", "harpunu", "a", "bodec", "s", "hákem", "a",
        "stařec", "si", "hodil", "přes", "rameno", "stěžeň", "se", "svinutou",
        "plachtou", "Nechcete", "kávu", "zeptal", "se", "chlapec", "Naložíme",
        "věci", "do", "člunu", "a", "pak", "se", "na", "ni", "někde", "stavíme",
        "Vypili", "kávu", "z", "plechovek", "od", "kondensovaného", "mléka",
        "v", "podniku", "otevřeném", "časně", "ráno", "pro", "rybáře", "Jak",
        "jste", "se", "vyspal", "dědo", "otázal", "se", "chlapec", "Teď", "se",
        "pomalu", "probouzel", "třebaže", "mu", "bylo", "ještě", "za", "těžko",
        "probrat", "se", "ze", "spánku", "Výborně", "Manoline", "odpověděl",
        "mu", "stařec", "Dneska", "mám", "pocit", "že", "to", "dopadne",
        "dobře", "Já", "taky", "přidal", "se", "chlapec", "Musím", "teď", "pro",
        "naše", "sardinky", "a", "pro", "vaše", "čerstvé", "návnady", "On",
        "si", "nosí", "výstroj", "sám", "Nikdy", "nechce", "aby", "mu", "něco",
        "nesl", "někdo", "druhý", "To", "my", "dva", "jsme", "jiní", "řekl",
        "stařec", "Nechal", "jsem", "tě", "nosit", "věci", "když", "ti", "bylo",
        "pět", "let", "Já", "vím", "přikývl", "chlapec", "Hned", "se", "vrátím",
        "Dejte", "si", "ještě", "jednu", "kávu", "Máme", "tady", "úvěr",
        "Odešel", "bos", "přes", "korálové", "skály", "k", "ledárně", "kde",
        "měl", "uloženou", "návnadu", "Stařec", "pomalu", "srkal", "kávu", "To",
        "bylo", "všechno", "co", "za", "celý", "den", "pozře", "a", "on",
        "věděl", "že", "ji", "musí", "vypít", "Dávno", "ho", "už", "teď",
        "omrzelo", "jíst", "a", "nikdy", "si", "s", "sebou", "nebral", "nic",
        "k", "obědu", "Měl", "na", "přídi", "loďky", "láhev", "vody", "a", "to",
        "bylo", "všechno", "co", "na", "celý", "den", "potřeboval", "Chlapec",
        "se", "mezitím", "vrátil", "se", "sardinkami", "a", "s", "dvěma",
        "návnadami", "zabalenými", "do", "novin", "a", "oba", "pak", "sešli",
        "po", "stezičce", "k", "loďce", "cítíce", "pod", "nohama", "omletý",
        "písek", "nadzdvihli", "člun", "a", "sešoupli", "jej", "do", "vody",
        "Dobrý", "lov", "dědo", "Dobrý", "lov", "poděkoval", "stařec",
        "Navlekl", "provazové", "smyčky", "vesel", "na", "kolíkové", "čepy",
        "a", "nakláněje", "se", "dopředu", "proti", "záběrům", "vesel", "začal",
        "veslovat", "ze", "zátoky", "ven", "do", "tmy", "Z", "ostatních",
        "pláží", "vyplouvaly", "na", "moře", "i", "jiné", "čluny", "a",
        "stařec", "slyšel", "jak", "se", "jejich", "vesla", "hrouží", "a",
        "zabírají", "i", "když", "je", "teď", "kdy", "se", "měsíc", "schoval",
        "za", "kopce", "nemohl", "vidět", "Občas", "někdo", "v", "některém",
        "člunu", "promluvil", "Ale", "většina", "člunů", "plula", "mlčenlivě",
        "až", "na", "pleskání", "vesel", "Rozptýlily", "se", "jakmile",
        "vypluly", "z", "ústí", "zátoky", "a", "každý", "si", "to", "namířil",
        "do", "té", "části", "oceánu", "kde", "doufal", "narazit", "na", "ryby",
        "Stařec", "si", "byl", "vědom", "že", "popluje", "daleko", "zanechal",
        "pach", "pevniny", "za", "sebou", "a", "vyrazil", "vstříc",
        "předjitřní", "vůni", "oceánu", "Viděl", "ve", "vodě", "fosforeskovat",
        "chaluhy", "když", "vesloval", "tou", "částí", "oceánu", "které",
        "rybáři", "říkali", "veliká", "studně", "protože", "se", "tu", "náhle",
        "otvírala", "sedmistysáhová", "hlubina", "kde", "se", "shlukovaly",
        "ryby", "všeho", "druhu", "stahované", "sem", "vírem", "jenž",
        "vznikal", "nárazy", "proudu", "o", "srázné", "hradby", "na", "dne",
        "oceánu", "Soustředili", "se", "tu", "mořští", "ráčci", "a", "ryby",
        "sloužící", "za", "vnadidlo", "a", "někdy", "v", "nejhlubších",
        "děrách", "hejna", "šípovitých", "hlavonožců", "kteří", "v", "noci",
        "vyplouvali", "až", "pod", "hladinu", "kde", "se", "jimi", "živily",
        "všechny", "kolem", "táhnoucí", "ryby", "Stařec", "cítil", "ve", "tmě",
        "nadcházející", "jitro", "a", "jak", "vesloval", "slyšel", "frčení",
        "se", "kterým", "létavé", "ryby", "vyskakovaly", "z", "vody", "a",
        "sykot", "jejich", "ztuha", "roztažených", "křídel", "když", "se",
        "vznášely", "ve", "tmě", "pryč", "Cítil", "k", "létavým", "rybám",
        "velkou", "náklonnost", "byly", "to", "na", "oceánu", "jeho",
        "největší", "přítelkyně", "Litoval", "ptáky", "zvlášť", "drobné", "a",
        "útlé", "tmavé", "mořské", "vlaštovky", "které", "věčně", "kroužily",
        "a", "vyhlížely", "a", "skoro", "nikdy", "nic", "nenalézaly", "a",
        "myslel", "si", "Ptáci", "mají", "těžší", "život", "než", "my", "až",
        "na", "dravce", "a", "na", "ty", "co", "jsou", "statní", "a", "silní",
        "Proč", "vlastně", "udělali", "tak", "útlé", "a", "něžné", "ptáčky",
        "jako", "jsou", "tyhle", "mořské", "vlaštovky", "když", "vřava",
        "oceánu", "dokáže", "být", "tak", "ukrutná", "Spousta", "vod", "je",
        "laskavá", "a", "velice", "krásná", "Ale", "dokáže", "být", "tak",
        "ukrutná", "a", "vymrštit", "se", "tak", "náhle", "a", "takovíhle",
        "ptáčci", "kteří", "se", "vznášejí", "hrouží", "do", "vln", "a",
        "shánějí", "potravu", "s", "tím", "svým", "tenkým", "smutným",
        "pípáním", "jsou", "pro", "ni", "příliš", "něžní", "Myslel", "na",
        "moře", "vždycky", "v", "ženském", "rodě", "jako", "na", "la", "mar",
        "jak", "mu", "lidé", "říkají", "ve", "španělštině", "když", "je",
        "milují", "Někdy", "o", "té", "mořské", "spoustě", "mluví", "špatně",
        "i", "ti", "kdož", "ji", "milují", "ale", "říkají", "to", "vždycky",
        "jako", "by", "hovořili", "o", "ženě", "Někteří", "mladší", "rybáři",
        "ti", "co", "užívali", "bojí", "jako", "splávků", "pro", "své", "šňůry",
        "a", "měli", "motorové", "čluny", "koupené", "když", "jim", "žraloci",
        "játra", "vynesla", "hodně", "peněz", "mluvili", "o", "moři", "v",
        "mužském", "rodě", "říkali", "el", "mar", "Mluvili", "o", "něm", "jako",
        "o", "nějakém", "soupeři", "nebo", "o", "zeměpisném", "názvu", "nebo",
        "dokonce", "jako", "o", "nepříteli", "Ale", "stařec", "na", "tu",
        "vodní", "spoustu", "myslil", "vždycky", "jako", "na", "ženskou",
        "bytost", "která", "člověku", "věnuje", "nebo", "odpírá", "velikou",
        "přízeň", "a", "jestliže", "provádí", "divoké", "či", "zlomyslné",
        "kousky", "je", "to", "jen", "proto", "že", "nemůže", "jinak", "Měsíc",
        "na", "ni", "působí", "jako", "na", "ženu", "myslel", "si", "Vesloval",
        "vytrvale", "a", "nenamáhal", "se", "při", "tom", "protože",
        "nepřekročil", "svou", "obvyklou", "rychlost", "a", "hladina", "oceánu",
        "byla", "hladká", "až", "na", "občasná", "zavíření", "v", "proudu",
        "Nechal", "proud", "aby", "ze", "třetiny", "pracoval", "za", "něj", "a",
        "když", "začalo", "svítat", "shledal", "že", "se", "už", "dostal",
        "dál", "než", "v", "tuhle", "hodinu", "doufal", "Zkoušel", "jsem", "ty",
        "hluboké", "studně", "celý", "týden", "a", "nic", "z", "toho", "nebylo",
        "myslel", "si", "Dnes", "se", "vypravím", "hloub", "do", "moře", "kde",
        "jsou", "hejna", "tuňáků", "bonitos", "a", "albacore", "a", "mezi",
        "nimi", "se", "snad", "najde", "nějaký", "pořádný", "kus", "Než", "se",
        "opravdu", "rozednilo", "měl", "už", "vnadidla", "ve", "vodě", "a",
        "dal", "se", "unášet", "proudem", "Jednu", "návnadu", "spustil", "do",
        "hloubky", "čtyřiceti", "sáhů", "Druhou", "do", "pětasedmdesáti", "a",
        "třetí", "a", "čtvrtá", "se", "vznášela", "v", "modré", "vodě", "v",
        "hloubce", "jednoho", "sta", "a", "stopětadvaceti", "sáhů", "Všechny",
        "ryby", "kterých", "užil", "jako", "vnadidla", "visely", "hlavou",
        "dolů", "provlečeny", "dříkem", "háku", "pevně", "svázány", "a",
        "sešity", "a", "vyčnívající", "zahnutá", "část", "háku", "a", "hrot",
        "byly", "pokryty", "čerstvými", "sardinkami", "Všechny", "sardinky",
        "byly", "navlečeny", "na", "hák", "za", "oba", "boční", "otvory", "tak",
        "že", "tvořily", "na", "vyčnívající", "oceli", "poloviční", "věnec",
        "Na", "háku", "nebylo", "jediné", "místečko", "jehož", "se", "mohla",
        "veliká", "ryba", "dotknout", "které", "by", "sladce", "nezavánělo",
        "a", "příjemně", "nechutnalo", "Chlapec", "mu", "dal", "dva", "čerstvé",
        "malé", "tuňáky", "nebo", "albacory", "kteří", "viseli", "na", "dvou",
        "nejhlubších", "šňůrách", "jako", "olovnice", "a", "na", "dvou",
        "ostatních", "měl", "dva", "kranasy", "jednoho", "velkého", "modrého",
        "a", "druhého", "zlatavého", "kterých", "užil", "už", "dříve", "ale",
        "byli", "ještě", "v", "dobrém", "stavu", "a", "výborné", "sardinky",
        "jim", "dodávaly", "vůně", "a", "přitažlivosti", "Na", "každou",
        "šňůru", "silnou", "jako", "tlustá", "tužka", "byl", "smyčkou",
        "přivázán", "čerstvě", "uříznutý", "klacek", "který", "by", "se",
        "ponořil", "kdyby", "ryba", "ťukla", "o", "vnadidlo", "nebo",
        "zatahala", "za", "ně", "a", "každá", "šňůra", "měla", "dva",
        "čtyřicetisáhové", "kotouče", "které", "se", "daly", "navázat", "na",
        "ostatní", "zásobní", "kotouče", "takže", "v", "případě", "potřeby",
        "mohla", "chycená", "ryba", "odvinout", "přes", "tři", "sta", "sáhů",
        "šňůry", "Teď", "stařec", "pozoroval", "přes", "pažení", "loďky", "jak",
        "se", "tři", "klacky", "noří", "do", "vody", "a", "zlehka", "vesloval",
        "aby", "udržel", "šňůry", "svisle", "napjaté", "a", "v", "patřičných",
        "hloubkách", "Bylo", "už", "docela", "světlo", "a", "každou", "chvíli",
        "už", "muselo", "vyjít", "slunce", "Slunce", "vystoupilo", "krajíčkem",
        "z", "moře", "a", "stařec", "uviděl", "ostatní", "čluny", "nízko", "na",
        "vodě", "a", "hezky", "daleko", "směrem", "ke", "břehu", "jak", "se",
        "rozptýlily", "po", "šířce", "proudu", "Pak", "slunce", "vysvitlo",
        "jasněji", "a", "jeho", "záře", "dopadla", "na", "vodu", "a", "pak",
        "když", "se", "vyhouplo", "celé", "odráželo", "mu", "je", "hladké",
        "moře", "do", "očí", "až", "jej", "prudce", "rozbolely", "a", "on",
        "vesloval", "nedívaje", "se", "do", "něho", "Hleděl", "do", "vody", "a",
        "pozoroval", "šňůry", "spadající", "dolů", "do", "zšeřelé", "hloubky",
        "Nikdo", "jiný", "je", "nedokázal", "udržet", "rovnej", "i", "tak",
        "aby", "ve", "všech", "vrstvách", "temnoty", "vodního", "proudění",
        "přesně", "tam", "kde", "chtěl", "čekalo", "vnadidlo", "na", "každou",
        "rybu", "která", "by", "plula", "kolem", "Jiní", "rybáři", "si", "je",
        "nechali", "brát", "proudem", "a", "často", "měli", "vnadidlo", "v",
        "hloubce", "šedesáti", "sáhů", "když", "byli", "přesvědčeni", "že",
        "dosáhli", "stovky", "To", "já", "myslel", "si", "stařec", "s", "nimi",
        "zacházím", "přesně", "Jenomže", "už", "nemám", "štěstí", "Ale", "kdož",
        "ví", "Možná", "dnes", "Každý", "den", "přináší", "něco", "nového",
        "Mít", "štěstí", "je", "lepší", "Ale", "já", "budu", "radši",
        "svědomitý", "Když", "pak", "člověka", "potká", "štěstí", "je", "aspoň",
        "připraven", "Slunce", "zatím", "vystoupilo", "o", "dvě", "hodiny",
        "výše", "a", "už", "ho", "tak", "nebolelo", "do", "očí", "když", "se",
        "podíval", "na", "východ", "V", "dohledu", "byly", "už", "jen", "tři",
        "čluny", "které", "se", "rýsovaly", "velmi", "nízko", "a", "daleko",
        "ke", "břehu", "Celý", "život", "mě", "časné", "slunce", "pálí", "do",
        "očí", "pomyslil", "si", "stařec", "Ale", "oči", "mi", "slouží",
        "ještě", "dobře", "Večer", "se", "můžu", "podívat", "přímo", "do",
        "slunce", "a", "nezatmí", "se", "mi", "před", "očima", "A", "večer",
        "má", "slunce", "větší", "sílu", "Jenže", "ráno", "to", "bolí", "Vtom",
        "si", "všiml", "ptáka", "fregatky", "který", "před", "ním", "kroužil",
        "na", "obloze", "na", "dlouhých", "černých", "perutích", "Pták",
        "náhle", "prudce", "klesl", "spustil", "se", "dolů", "s", "křídly",
        "přitaženými", "k", "tělu", "a", "pak", "zase", "zakroužil", "Něco",
        "tam", "má", "řekl", "si", "stařec", "nahlas", "Jenom", "tak", "se",
        "nedívá", "Vesloval", "zvolna", "a", "vytrvale", "tam", "kde", "pták",
        "kroužil", "Nepospíchal", "a", "udržoval", "šňůry", "rovně", "ve",
        "svislé", "poloze", "Ale", "předstihl", "trochu", "proud", "takže",
        "stále", "ještě", "lovil", "jaksepatří", "třebaže", "o", "něco",
        "rychleji", "než", "by", "lovil", "kdyby", "se", "nesnažil", "dát",
        "se", "vést", "ptákem", "Pták", "se", "vznesl", "ve", "vzduchu", "výše",
        "a", "opět", "zakroužil", "s", "nepohnutými", "křídly", "Pak", "se",
        "náhle", "vrhl", "dolů", "a", "stařec", "uviděl", "létavé", "ryby",
        "vystřelit", "z", "vody", "a", "zoufale", "plachtit", "po", "hladině",
        "Dorády", "řekl", "si", "stařec", "nahlas", "Velké", "dorády", "Složil",
        "vesla", "do", "loďky", "a", "vytáhl", "zpod", "paloubky", "na",
        "přídi", "tenkou", "šňůru", "Končila", "drátěným", "nástavcem", "a",
        "středně", "velkou", "udicí", "kterou", "navnadil", "jednou", "ze",
        "sardinek", "Hodil", "ji", "přes", "boční", "pažení", "a", "pak", "ji",
        "přivázal", "ke", "kruhu", "přišroubovanému", "na", "zádi", "Pak",
        "navnadil", "ještě", "jednu", "šňůru", "a", "nechal", "ji", "stočenou",
        "ve", "stínu", "přídě", "Dal", "se", "zase", "do", "veslování", "a",
        "pozoroval", "černého", "ptáka", "s", "dlouhými", "perutěmi", "který",
        "teď", "kroužil", "nízko", "nad", "vodou", "Jak", "ho", "tak",
        "pozoroval", "pták", "se", "opět", "vrhl", "dolů", "s", "křídly",
        "přitaženými", "k", "tělu", "pro", "střemhlavý", "pád", "a", "pak",
        "jimi", "začal", "divoce", "a", "bezvýsledně", "máchat", "v", "honbě",
        "za", "létavými", "rybami", "Stařec", "viděl", "lehké", "vyboulení",
        "vody", "zdvíhané", "velkými", "dorádami", "jak", "pronásledovaly",
        "unikající", "ryby", "Dorády", "brázdily", "vodu", "pod", "čarou",
        "jejich", "letu", "a", "doženou", "se", "ve", "vodě", "plnou",
        "rychlostí", "na", "místo", "kam", "ryby", "dopadnou", "Je", "to",
        "pořádné", "hejno", "dorád", "pomyslel", "si", "stařec", "Jsou",
        "rozptýleny", "do", "šířky", "a", "létavé", "ryby", "mají", "malé",
        "vyhlídky", "Pták", "nemá", "žádnou", "vyhlídku", "Létavé", "ryby",
        "jsou", "na", "něho", "příliš", "veliké", "a", "příliš", "rychlé",
        "Pozoroval", "jak", "létavé", "ryby", "znovu", "a", "znovu",
        "prorážejí", "hladinu", "a", "jak", "se", "pták", "bezvýsledně",
        "snaží", "To", "hejno", "mi", "uteklo", "pomyslel", "si", "Vyrazily",
        "moc", "daleko", "a", "moc", "rychle", "Ale", "možná", "že", "dostanu",
        "některou", "co", "od", "nich", "zabloudila", "a", "možná", "že", "je",
        "jim", "nablízku", "moje", "velká", "ryba", "Někde", "ta", "má",
        "veliká", "ryba", "být", "musí", "Oblaka", "nad", "pevninou", "se",
        "teď", "nakupila", "jako", "hory", "a", "pobřeží", "se", "změnilo", "v",
        "dlouhou", "zelenou", "čáru", "za", "kterou", "se", "zvedaly",
        "šedomodré", "kopce", "Voda", "teď", "měla", "barvu", "temně", "modrou",
        "tak", "temnou", "že", "byla", "skoro", "fialová", "Kdy", "ž", "se",
        "podíval", "do", "hloubky", "viděl", "v", "tmavé", "vodě", "jakoby",
        "prosátý", "červený", "plankton", "a", "zvláštní", "světlo", "vrhané",
        "teď", "sluncem", "Pozoroval", "své", "šňůry", "a", "hleděl", "jak",
        "splývají", "přímo", "dolů", "až", "ve", "vodě", "mizely", "z",
        "dohledu", "a", "byl", "rád", "že", "vidí", "tolik", "planktonu",
        "protože", "to", "znamenalo", "ryby", "Zvláštní", "světlo", "kterým",
        "slunce", "teď", "když", "stálo", "výše", "prozařovalo", "vodu",
        "znamenalo", "pěkné", "počasí", "právě", "tak", "jako", "tvar", "oblak",
        "nad", "pevninou", "Ale", "pták", "se", "zatím", "dostal", "skoro", "z",
        "dohledu", "a", "na", "hladině", "nebylo", "vidět", "nic", "než",
        "několik", "pruhů", "žlutých", "sluncem", "vyrudlých", "sargasových",
        "chaluh", "a", "fialový", "dokonale", "utvářený", "duhově", "hrající",
        "rosolovitý", "měchýř", "žahavého", "trubejše", "zvaného",
        "portugalský", "bitevník", "plynoucí", "po", "vodě", "těsně", "v",
        "blízkosti", "člunu", "Převalil", "se", "na", "bok", "a", "pak", "se",
        "zase", "narovnal", "Plynul", "si", "vesele", "jako", "bublina", "a",
        "vláčel", "za", "sebou", "na", "loket", "ve", "vodě", "svá", "dlouhá",
        "jedovatá", "fialová", "vlákna", "Agua", "malá", "řekl", "člověk", "Ty",
        "děvko", "S", "místa", "kde", "se", "lehce", "opřel", "do", "vesel",
        "se", "zadíval", "dolů", "do", "vody", "a", "viděl", "drobné", "rybky",
        "zbarvené", "stejně", "jako", "vláčející", "se", "vlákna", "které",
        "pluly", "mezi", "vlákny", "a", "pod", "skvrnkou", "stínu", "vrhaného",
        "vznášející", "se", "bublinou", "Její", "jed", "na", "ně", "neplatil",
        "Ale", "na", "člověka", "ano", "a", "kdyby", "se", "některé", "vlákno",
        "zachytilo", "na", "šňůře", "a", "přilnulo", "tam", "slizké", "a",
        "fialové", "až", "bude", "starý", "přitahovat", "rybu", "naskočily",
        "by", "mu", "na", "pažích", "a", "na", "rukou", "puchýře", "a",
        "vyrážky", "podobně", "jako", "když", "člověka", "žahne", "list",
        "kulčiby", "nebo", "škumpy", "jedovaté", "Ale", "tyhle", "kožní",
        "otravy", "které", "působí", "agua", "malá", "se", "objeví", "jedna",
        "dvě", "a", "šlehnou", "jako", "bič", "Duhově", "hrající", "bubliny",
        "byly", "krásné", "Ale", "byla", "to", "ta", "nejproradnější", "krása",
        "na", "moři", "a", "stařec", "se", "rád", "díval", "jak", "je", "žerou",
        "velké", "mořské", "želvy", "Želvy", "je", "uvidí", "přiblíží", "se",
        "k", "nim", "zpředu", "pak", "zavřou", "oči", "takže", "jsou", "úplně",
        "obrněny", "a", "sežerou", "je", "i", "s", "vlákny", "a", "se", "vším",
        "všudy", "Stařec", "se", "rád", "díval", "jak", "je", "žerou", "želvy",
        "a", "rád", "po", "nich", "šlapal", "na", "břehu", "po", "bouři", "a",
        "poslouchal", "jak", "lupají", "když", "na", "ně", "stoupne",
        "zrohovatělými", "chodidly", "Miloval", "zelené", "želvy", "a",
        "zobanovité", "želvy", "karetové", "elegantní", "a", "rychlé", "a",
        "velmi", "ceněné", "a", "cítil", "přátelské", "pohrdání", "pro",
        "ohromné", "tupé", "hlavaté", "karety", "zbabělé", "ve", "svých",
        "krunýřích", "podivné", "ve", "svém", "milování", "a", "blaženě",
        "požírající", "se", "zavřenýma", "očima", "žahavé", "trubejše",
        "Nevěřil", "u", "želv", "na", "žádnou", "mystiku", "třebaže", "je",
        "mnoho", "let", "jezdíval", "ve", "člunu", "lovit", "Litoval", "je",
        "všechny", "i", "ty", "s", "obrovskými", "pancíři", "které", "byly",
        "dlouhé", "jako", "loďka", "a", "vážily", "celou", "tunu", "Většina",
        "lidí", "k", "želvám", "v", "srdci", "nic", "necítí", "protože",
        "želví", "srdce", "bije", "ještě", "hodiny", "poté", "co", "byla",
        "želva", "rozříznuta", "a", "vyvržena", "Ale", "stařec", "si", "myslel",
        "Já", "mám", "zrovna", "takové", "srdce", "i", "nohy", "a", "ruce",
        "mám", "jako", "jsou", "jejich", "Jedl", "jejich", "bílá", "vejce",
        "aby", "nabyl", "síly", "Jedl", "je", "po", "celý", "květen", "aby",
        "byl", "v", "září", "a", "v", "říjnu", "dost", "silný", "na", "opravdu",
        "velké", "ryby", "Pil", "také", "každý", "den", "šálek", "rybího",
        "tuku", "ze", "žralocích", "jater", "z", "plechového", "barelu", "v",
        "kůlně", "kde", "si", "mnoho", "rybářů", "ukládalo", "výstroj", "Stál",
        "tam", "pro", "všechny", "rybáře", "kteří", "o", "něj", "měli", "zájem",
        "Většině", "z", "nich", "se", "hnusila", "jeho", "chuť", "Ale",
        "nebylo", "to", "o", "nic", "horší", "než", "vstávat", "tak", "časně",
        "jako", "museli", "a", "bylo", "to", "výborné", "proti", "všem",
        "druhům", "nachlazení", "a", "chřipek", "a", "prospívalo", "to", "očím",
        "Teď", "stařec", "pohlédl", "vzhůru", "a", "uviděl", "že", "pták",
        "krouží", "zase", "Objevil", "ryby", "řekl", "si", "nahlas", "Létavé",
        "ryby", "se", "však", "nad", "hladinou", "neukázaly", "ani", "se", "tu",
        "nehemžily", "drobné", "rybičky", "Ale", "jak", "se", "tak", "stařec",
        "díval", "vyhoupl", "se", "do", "povětří", "malý", "tuňák", "otočil",
        "se", "a", "padl", "do", "vody", "hlavou", "napřed", "Zablýskl", "se",
        "ve", "slunci", "jako", "stříbro", "a", "jakmile", "dopadl", "zpátky",
        "vyskočil", "další", "a", "zase", "další", "a", "skákali", "tak", "se",
        "všech", "stran", "vířili", "vodu", "a", "vrhali", "se", "dlouhými",
        "skoky", "po", "rybičkách", "Kroužili", "kolem", "nich", "a", "štvali",
        "je", "před", "sebou", "Jestli", "nepoplují", "moc", "rychle",
        "dostanu", "se", "mezi", "ně", "pomyslel", "si", "stařec", "a",
        "pozoroval", "jak", "hejno", "zpěňuje", "vodu", "do", "bělá", "a",
        "jak", "se", "pták", "náhle", "spustil", "dolů", "a", "vrhl", "se",
        "na", "drobné", "sardinky", "které", "panický", "strach", "vypudil",
        "až", "ke", "hladině", "Ten", "pták", "je", "ohromný", "pomocník",
        "řekl", "si", "stařec", "Právě", "v", "tom", "okamžiku", "se", "mu",
        "šňůra", "uvázaná", "na", "zádi", "napjala", "pod", "nohou", "kde",
        "si", "před", "chvílí", "ponechal", "volnou", "smyčku", "Pustil",
        "vesla", "a", "když", "uchopil", "šňůru", "pevně", "a", "začal", "ji",
        "soukat", "k", "sobě", "ucítil", "tíži", "a", "chvějivý", "tah",
        "malého", "tuňáka", "Jak", "táhl", "chvění", "sílelo", "a", "pak", "ve",
        "vodě", "uviděl", "jeho", "modrý", "hřbet", "a", "jeho", "zlaté",
        "boky", "než", "jej", "přehodil", "přes", "pažení", "do", "člunu",
        "Ležel", "na", "zádi", "v", "slunci", "jako", "vysoustruhovaný", "z",
        "jednoho", "kusu", "do", "tvaru", "granátu", "veliké", "a", "nechápavé",
        "oči", "dokořán", "a", "utloukal", "se", "k", "smrti", "o", "podlážku",
        "člunu", "prudkými", "chvějivými", "údery", "čistě", "vykrojeného", "a",
        "rychle", "se", "mrskajícího", "ocasu", "Stařec", "ho", "z", "milosti",
        "klepl", "přes", "hlavu", "a", "odkopl", "jeho", "dosud", "se",
        "cukající", "tělo", "do", "stínu", "pod", "zadní", "paloubku",
        "Albacore", "řekl", "si", "nahlas", "To", "bude", "báječné", "vnadidlo",
        "Váží", "dobrých", "deset", "liber", "Nevzpomínal", "si", "už", "kdy",
        "vlastně", "začal", "sám", "k", "sobě", "mluvit", "nahlas", "Kdysi",
        "dávno", "si", "o", "samotě", "zpíval", "a", "zpívával", "si", "někdy",
        "v", "noci", "když", "míval", "hlídku", "na", "rybářských", "kutrech",
        "či", "na", "bárkách", "lovících", "želvy", "a", "když", "sám",
        "kormidloval", "Začal", "nejspíš", "mluvit", "nahlas", "sám", "pro",
        "sebe", "když", "s", "ním", "přestal", "jezdit", "chlapec", "Ale",
        "nepamatoval", "se", "už", "Když", "ry", "baříval", "s", "chlapcem",
        "mluvili", "na", "sebe", "obyčejně", "jen", "co", "bylo", "nutné",
        "Hovořívali", "spolu", "v", "noci", "nebo", "když", "jim", "ve",
        "vyplutí", "zabránila", "bouře", "či", "špatné", "počasí", "Na", "moři",
        "se", "považovalo", "za", "ctnost", "nemluvit", "když", "to", "není",
        "nutné", "a", "stařec", "to", "tak", "vždycky", "bral", "a",
        "dodržoval", "to", "Ale", "teď", "když", "s", "ním", "nebyl", "nikdo",
        "komu", "by", "to", "mohlo", "vadit", "vyslovoval", "hlasitě", "své",
        "myšlenky", "často", "Kdyby", "mě", "slyšeli", "mluvit", "ostatní",
        "pomysleli", "by", "si", "že", "mně", "přeskočilo", "řekl", "nahlas",
        "Ale", "mně", "nepřeskočilo", "a", "takje", "mi", "to", "jedno",
        "Ostatně", "boháči", "mají", "na", "svých", "lodích", "radu", "aby",
        "na", "ně", "mluvila", "a", "hlásila", "jim", "výsledky", "baseballu",
        "Jenže", "teď", "není", "čas", "myslet", "na", "baseball", "napadlo",
        "ho", "Teď", "je", "čas", "myslet", "jenom", "najedno", "Na", "to",
        "pro", "co", "jsem", "se", "narodil", "Poblíž", "toho", "hejna", "by",
        "mohla", "být", "nějaká", "pořádná", "Chytil", "jsem", "jenom",
        "nějakého", "zbloudilce", "od", "těch", "albacorů", "co", "se", "tam",
        "krmili", "Ale", "mají", "dnes", "nějak", "na", "pilno", "a", "dostali",
        "se", "daleko", "Všechno", "co", "se", "dnes", "ukáže", "na", "hladině",
        "má", "nějak", "naspěch", "a", "všechno", "k", "severovýchodu", "Je",
        "to", "snad", "tou", "denní", "dobou", "Nebo", "je", "to", "nějaká",
        "známka", "změny", "počasí", "kterou", "neznám", "Neviděl", "už",
        "zeleň", "pobřeží", "jenom", "vršky", "modravých", "kopců", "které",
        "se", "zdály", "bílé", "jako", "by", "měly", "sněžné", "čepičky", "a",
        "oblaka", "která", "se", "nad", "nimi", "tyčila", "jako", "vysoké",
        "sněžné", "pohoří", "Moře", "bylo", "velice", "temné", "a", "světlo",
        "se", "ve", "vodě", "rozkládalo", "jako", "v", "hranolu", "Myriády",
        "teček", "planktonu", "se", "rozplynuly", "v", "záři", "vysokého",
        "slunce", "a", "stařec", "teď", "viděl", "v", "modré", "hloubce",
        "jenom", "obrovitá", "prismata", "lámajících", "se", "paprsků", "a",
        "své", "šňůry", "splývající", "kolmo", "do", "vody", "na", "míli",
        "hluboké", "Tuňáci", "rybáři", "říkali", "všem", "rybám", "toho",
        "druhu", "tuňáci", "a", "rozlišovali", "je", "příslušnými", "jmény",
        "jenom", "když", "je", "přišli", "prodat", "nebo", "vyměnit", "za",
        "návnadu", "tuňáci", "opět", "klesli", "dolů", "Slunce", "teď",
        "pálilo", "a", "starý", "je", "cítil", "v", "zátylku", "a", "cítil",
        "jak", "mu", "při", "veslování", "stéká", "čůrkem", "po", "zádech",
        "pot", "Mohl", "bych", "se", "dát", "nést", "proudem", "pomyslel", "si",
        "usnout", "a", "navléknout", "si", "kličku", "šňůry", "na", "palec",
        "u", "nohy", "abych", "se", "probudil", "Ale", "dnes", "je", "to",
        "pětaosmdesát", "dní", "a", "měl", "bych", "dnes", "rybařit", "pořádně",
        "Právě", "v", "tom", "okamžiku", "jak", "tak", "pozoroval", "šňůry",
        "se", "jeden", "z", "vyčnívajících", "zelených", "klacků", "prudce",
        "potopil", "Ano", "řekl", "si", "ano", "a", "složil", "vesla", "do",
        "člunu", "tak", "aby", "člunem", "netrhl", "Sáhl", "po", "šňůře", "a",
        "ozkoušel", "ji", "jemně", "mezi", "palcem", "a", "ukazováčkem",
        "pravé", "ruky", "Necítil", "žádný", "tah", "ani", "tíhu", "a",
        "zlehka", "šňůru", "podržel", "Pak", "to", "přišlo", "znovu",
        "Tentokrát", "ucítil", "zkusmé", "škubnutí", "ani", "důrazné", "ani",
        "silné", "a", "poznal", "přesně", "oč", "jde", "V", "hloubce", "sta",
        "sáhů", "ožíral", "mečounovitý", "marlin", "sardinky", "zakrývající",
        "hrot", "a", "dřík", "udice", "v", "místě", "kde", "ručně", "kovaný",
        "hák", "vyčníval", "z", "hlavy", "malého", "tuňáka", "Stařec",
        "zlehýnka", "podržel", "šňůru", "a", "levičkou", "z", "ní", "citlivě",
        "vyprostil", "klacek", "Teď", "si", "ji", "mohl", "nechat", "probíhat",
        "mezi", "prsty", "aniž", "ryba", "cítila", "nejmenší", "napětí", "V",
        "téhle", "vzdálenosti", "od", "břehu", "a", "v", "tomhle", "měsíci",
        "musí", "být", "obrovská", "Jen", "je", "sněz", "rybo", "Sněz", "je",
        "Prosím", "tě", "je", "sněz", "Jsou", "tak", "čerstvé", "a", "ty",
        "jsi", "tam", "dvě", "stě", "metrů", "hluboko", "v", "té", "studené",
        "vodě", "a", "tmě", "Zakruž", "tam", "ve", "tmě", "ještě", "jednou",
        "vrať", "se", "a", "sněz", "je", "Ucítil", "lehké", "jemné", "cukání",
        "a", "pak", "prudší", "škubnutí", "asi", "když", "hlava", "některé",
        "sardinky", "nešla", "tak", "snadno", "odtrhnout", "s", "háku", "A",
        "pak", "nic", "Pojď", "pojď", "vábil", "ji", "starý", "nahlas", "Ještě",
        "jednou", "se", "obrať", "Jen", "si", "k", "nim", "přivoň", "Nejsou",
        "báječné", "Sněz", "je", "všechny", "a", "pak", "tě", "čeká", "tuňák",
        "Tuhý", "chladný", "a", "lákavý", "Nestyď", "se", "rybo", "Sněz", "je",
        "Čekal", "se", "šňůrou", "mezi", "palcem", "a", "ukazováčkem",
        "pozoroval", "ji", "zároveň", "s", "ostatními", "šňůrami", "protože",
        "ryba", "mohla", "vyplout", "výš", "nebo", "se", "ponořit", "hlouběji",
        "Pak", "ucítil", "opět", "to", "lehounké", "cukání", "Zabere",
        "pronesl", "stařec", "nahlas", "Kriste", "Ježíši", "ať", "zabere",
        "Ale", "ryba", "nezabrala", "Zmizela", "a", "stařec", "necítil", "nic",
        "Nemohla", "zmizet", "řekl", "Pánbůh", "ví", "že", "nemohla", "zmizet",
        "Bere", "zatáčku", "Možná", "že", "se", "už", "někdy", "chytila", "a",
        "ještě", "se", "na", "to", "pamatuje", "Pak", "ucítil", "jak", "sebou",
        "šňůra", "mírně", "trhla", "a", "byl", "šťasten", "To", "se", "jenom",
        "obracela", "potvrdil", "si", "Byl", "šťasten", "když", "cítil",
        "mírné", "cukání", "a", "pak", "ucítil", "prudké", "škubnutí", "a",
        "něco", "neuvěřitelně", "těžkého", "Byla", "to", "váha", "ryby", "a",
        "on", "popouštěl", "šňůru", "hloub", "hloub", "a", "hloub", "odvíjeje",
        "první", "ze", "zásobních", "kotoučů", "Jak", "se", "šňůra",
        "ponořovala", "klouzajíc", "mu", "mezi", "prsty", "cítil", "stařec",
        "neustále", "tu", "obrovskou", "tíži", "třebaže", "stisk", "jeho",
        "palce", "a", "ukazováčku", "byl", "téměř", "neznatelný", "To", "je",
        "ale", "ryba", "řekl", "si", "Drží", "teď", "tuňáka", "napříč", "v",
        "hubě", "a", "odnáší", "si", "ho", "pryč", "Pak", "se", "obrátí", "a",
        "spolkne", "ho", "pomyslel", "si", "To", "nahlas", "nevyslovil",
        "protože", "věděl", "že", "když", "člověk", "vysloví", "něco",
        "dobrého", "může", "to", "tím", "překazit", "Poznal", "jak", "ohromná",
        "ta", "ryba", "je", "a", "myslel", "na", "ni", "jak", "odplouvá",
        "temnotou", "s", "tuňákem", "křížem", "v", "hubě", "V", "tom",
        "okamžiku", "ucítil", "že", "ryba", "ustala", "v", "pohybu", "ale",
        "její", "tíhu", "cítil", "stále", "Pak", "ta", "tíha", "vzrostla", "a",
        "on", "popustil", "šňůru", "Stiskl", "ji", "na", "okamžik", "palcem",
        "a", "ukazováčkem", "napětí", "zesílilo", "a", "začalo", "tíhnout",
        "kolmo", "dolů", "Zabrala", "řekl", "nahlas", "Teď", "ji", "nechám",
        "aby", "to", "pořádně", "pozřela", "Nechal", "si", "šňůru",
        "proklouzávat", "mezi", "prsty", "zatím", "co", "levičkou", "sáhl",
        "dolů", "a", "navázal", "volný", "konec", "prvních", "dvou",
        "zásobních", "kotoučů", "další", "šňůry", "Teď", "byl", "připraven",
        "Měl", "teď", "v", "zásobě", "tři", "čtyřicetisáhové", "kotouče",
        "šňůry", "navíc", "ke", "kotouči", "který", "právě", "odvíjel",
        "Spolkni", "to", "ještě", "lip", "promluvil", "Spolkni", "to",
        "pořádně", "Spolkni", "to", "tak", "aby", "ti", "hrot", "háku",
        "pronikl", "do", "srdce", "a", "zabil", "tě", "pomyslel", "si",
        "Vypluj", "zlehka", "a", "nech", "do", "sebe", "vrazit", "harpunu",
        "Dobrá", "Jsi", "hotová", "Máš", "už", "toho", "krmení", "dost", "Teď",
        "vykřikl", "hlasitě", "a", "trhl", "prudce", "oběma", "rukama",
        "vybojoval", "si", "metr", "šňůry", "a", "pak", "se", "znovu", "a",
        "znovu", "chápal", "střídavě", "oběma", "rukama", "vytahovaného",
        "lana", "a", "komíhal", "se", "na", "něm", "veškerou", "silou", "paží",
        "i", "váhou", "svého", "těla", "vzepřeného", "jako", "čep", "Nic", "se",
        "nestalo", "Ryba", "prostě", "pomalu", "odplouvala", "a", "stařec",
        "ji", "nemohl", "přitáhnout", "ani", "o", "coul", "blíž", "k",
        "hladině", "Šňůru", "měl", "pevnou", "dělanou", "na", "těžké", "ryby",
        "a", "teď", "si", "ji", "přehodil", "přes", "záda", "a", "táhl", "až",
        "se", "napjala", "tak", "že", "od", "ní", "odstřikovaly", "kapičky",
        "vody", "Pak", "začala", "šňůra", "ve", "vodě", "pomalu", "syčet", "a",
        "on", "stále", "táhl", "vzpíraje", "se", "o", "veslařské", "sedátko",
        "a", "zakláněje", "se", "proti", "směru", "tahu", "Člun", "se",
        "pomalu", "hnul", "k", "severozápadu", "Ryba", "plula", "vytrvale", "a",
        "tak", "pomalu", "cestovali", "po", "klidném", "moři", "Ostatní",
        "vnadidla", "byla", "dosud", "ve", "vodě", "ale", "nedalo", "se", "nic",
        "dělat", "Kdyby", "tak", "se", "mnou", "byl", "chlapec", "řekl", "si",
        "stařec", "nahlas", "Ryba", "mě", "vzala", "do", "vleku", "a", "já",
        "tady", "trčím", "jako", "ouvazník", "pro", "vlečné", "lano", "Mohl",
        "bych", "šňůru", "přivázat", "Ale", "to", "by", "ji", "mohla",
        "přetrhnout", "Musím", "ji", "držet", "co", "mám", "síly", "a",
        "popouštět", "jí", "šňůru", "jak", "bude", "potřebovat", "Zaplať",
        "pánbůh", "že", "pluje", "dál", "a", "ne", "do", "hloubky", "Co", "si",
        "počnu", "jestli", "j", "i", "napadne", "ponořit", "se", "to", "nevím",
        "Co", "si", "počnu", "jestli", "zajede", "do", "hloubky", "a", "dodělá",
        "to", "taky", "nevím", "Ale", "něco", "už", "udělám", "Mám", "ještě",
        "spoustu", "možností", "Vzpíral", "šňůru", "přehozenou", "přes", "záda",
        "sledoval", "v", "jakém", "úhlu", "mizí", "pod", "hladinu", "a", "jak",
        "loďka", "nepřestajně", "míří", "k", "severozápadu", "Tohle", "ji",
        "zabije", "myslel", "si", "stařec", "Nevydrží", "to", "přece", "věčně",
        "Ale", "po", "čtyřech", "hodinách", "plula", "ryba", "vytrvale", "dál",
        "do", "oceánu", "vlekla", "člun", "a", "stařec", "se", "ještě", "stále",
        "houževnatě", "vzpíral", "tahu", "se", "šňůrou", "přes", "záda", "Když",
        "zabrala", "bylo", "poledne", "řekl", "nahlas", "A", "ještě", "jsem",
        "ji", "neviděl", "Předtím", "než", "ryba", "zabrala", "narazil", "si",
        "slaměný", "klobouk", "pevně", "na", "hlavu", "a", "teď", "ho", "řezal",
        "do", "čela", "Měl", "taky", "žízeň", "spustil", "se", "na", "kolena",
        "a", "opatrně", "aby", "neškubl", "šňůrou", "dolezl", "jak", "jen",
        "mohl", "daleko", "na", "příď", "a", "sáhl", "jednou", "rukou", "po",
        "láhvi", "s", "vodou", "Otevřel", "ji", "a", "trochu", "se", "napil",
        "Pak", "se", "opřel", "o", "příď", "a", "odpočíval", "Odpočíval",
        "vsedě", "na", "nevztyčeném", "stěžni", "s", "plachtou", "a", "snažil",
        "se", "nemyslet", "jen", "to", "vydržet", "Pak", "se", "ohlédl",
        "dozadu", "a", "zjistil", "že", "ztratil", "zemi", "z", "dohledu", "Na",
        "tom", "nezáleží", "pomyslel", "si", "Vždycky", "najdu", "cestu",
        "zpátky", "podle", "světel", "Havany", "Do", "západu", "slunce",
        "zbývají", "ještě", "dvě", "hodiny", "a", "do", "té", "doby", "možná",
        "ryba", "vyplave", "A", "jestli", "ne", "snad", "vyplave", "až",
        "vyjde", "měsíc", "A", "jestli", "neudělá", "ani", "to", "snad",
        "vyplave", "s", "východem", "slunce", "Nemám", "žádné", "křeče", "a",
        "cítím", "se", "silný", "To", "ona", "má", "hák", "v", "hubě", "Ale",
        "musí", "to", "být", "pane", "ryba", "když", "takhle", "táhne", "Má",
        "nejspíš", "hubu", "pevně", "semknutou", "kolem", "drátu", "Chtěl",
        "bych", "ji", "vidět", "Aspoň", "jednou", "bych", "ji", "chtěl",
        "uvidět", "abych", "věděl", "s", "čím", "mám", "co", "dělat", "Pokud",
        "mohl", "stařec", "určit", "z", "pozorování", "hvězd", "nezměnila",
        "ryba", "za", "celou", "tu", "noc", "směr", "ani", "rychlost", "Po",
        "západu", "slunce", "se", "ochladilo", "a", "starci", "uschl", "na",
        "zádech", "na", "pažích", "a", "na", "starých", "nohou", "studený",
        "pot", "Dříve", "během", "dne", "vzal", "pytel", "který", "přikrýval",
        "bedničku", "s", "návnadou", "a", "rozprostřel", "ho", "aby", "se",
        "na", "slunci", "usušil", "Po", "západu", "slunce", "si", "jej",
        "uvázal", "kolem", "krku", "tak", "že", "mu", "splýval", "na", "záda",
        "a", "opatrně", "jej", "podstrkal", "pod", "šňůru", "kterou", "měl",
        "teď", "přes", "ramena", "Podložil", "pytlem", "šňůru", "jako",
        "polštářkem", "a", "našel", "si", "způsob", "jak", "se", "opřít",
        "dopředu", "o", "příď", "takže", "měl", "skoro", "pohodlí", "Ve",
        "skutečnosti", "ta", "posice", "byla", "jenom", "o", "něco", "méně",
        "nesnesitelná", "jemu", "však", "připadala", "skoro", "pohodlná",
        "Nesvedu", "nic", "s", "ní", "a", "ona", "nesvede", "nic", "se", "mnou",
        "pomyslel", "si", "Aspoň", "tak", "dlouho", "dokud", "bude", "v",
        "tomhle", "pokračovat", "Jednou", "vstal", "vymočil", "se", "přes",
        "okraj", "loďky", "podíval", "se", "na", "hvězdy", "a", "zkontroloval",
        "si", "kurs", "Šňůra", "se", "rýsovala", "ve", "vodě", "už", "od",
        "jeho", "ramenou", "jako", "fosforeskující", "pruh", "Pluli", "teď",
        "pomaleji", "a", "záře", "světel", "z", "Havany", "nebyla", "tak",
        "jasná", "takže", "poznal", "že", "je", "nejspíš", "proud", "unáší",
        "směrem", "k", "východu", "Jestli", "ztratím", "světla", "Havany", "z",
        "dohledu", "bude", "to", "znamenat", "že", "míříme", "ještě", "dál",
        "na", "východ", "pomyslel", "si", "Jestli", "se", "ryba", "neodchýlila",
        "od", "svého", "směru", "měl", "bych", "je", "vidět", "ještě", "celé",
        "hodiny", "Rád", "bych", "věděl", "jak", "dnes", "dopadl", "baseball",
        "v", "první", "lize", "uvažoval", "v", "duchu", "Bylo", "by", "báječné",
        "mít", "při", "tomhle", "rádio", "Pak", "se", "vzpamatoval", "na", "to",
        "myslíš", "pořád", "Mysli", "na", "to", "co", "děláš", "Nesmíš",
        "provést", "žádnou", "hloupost", "Potom", "pronesl", "nahlas",
        "Kdybych", "tady", "tak", "měl", "chlapce", "Aby", "mi", "pomohl", "a",
        "tohle", "viděl", "Nikdo", "by", "na", "stará", "kolena", "neměl",
        "být", "sám", "uvažoval", "Ale", "není", "vyhnutí", "Nesmím",
        "zapomenout", "sníst", "toho", "tuňáka", "než", "se", "zkazí", "abych",
        "se", "udržel", "při", "síle", "Nezapomeň", "bez", "ohledu", "na", "to",
        "že", "se", "ti", "do", "něho", "vůbec", "nechce", "musíš", "ho",
        "ráno", "sníst", "Nezapomeň", "připomínal", "si", "v", "duchu", "Během",
        "noci", "se", "k", "člunu", "přiblížily", "dvě", "plískavice", "a",
        "on", "je", "slyšel", "jak", "se", "převalují", "a", "odfrkují", "Byl",
        "s", "to", "rozeznat", "odfrkování", "samce", "od", "vzdychavého",
        "frkání", "samice", "To", "jsou", "dobří", "tvorové", "řekl", "si",
        "Hrají", "si", "a", "laškují", "a", "mají", "jeden", "druhého", "rádi",
        "Jsou", "naši", "bratři", "jako", "létavé", "ryby", "Pak", "začal",
        "litovat", "velikou", "rybu", "kterou", "chytil", "na", "hák", "Je",
        "báječná", "a", "tak", "podivná", "a", "kdo", "ví", "jak", "je",
        "stará", "myslel", "si", "Ještě", "nikdy", "jsem", "neměl", "co",
        "dělat", "s", "tak", "silnou", "rybou", "nebo", "s", "rybou", "která",
        "by", "si", "vedla", "tak", "divně", "Snad", "je", "příliš", "moudrá",
        "na", "to", "aby", "skákala", "Strhala", "by", "mě", "kdyby", "začala",
        "skákat", "nebo", "se", "najednou", "divoce", "utrhla", "Ale", "možná",
        "že", "se", "už", "mockrát", "chytila", "a", "ví", "že", "musí",
        "bojovat", "právě", "takhle", "Nemůže", "vědět", "že", "proti", "ní",
        "stojí", "jen", "jeden", "člověk", "a", "zeje", "starý", "Ale", "jaký",
        "to", "je", "obr", "a", "kolik", "vynese", "na", "trhu", "jestli", "má",
        "dobré", "maso", "Zabral", "na", "vnadidlo", "jako", "samec", "a",
        "táhne", "jako", "samec", "a", "bojuje", "beze", "vší", "paniky", "Rád",
        "bych", "věděl", "jestli", "má", "v", "hlavě", "nějaký", "plán", "nebo",
        "jestli", "je", "právě", "tak", "zoufalý", "jako", "jsem", "já",
        "Vzpomněl", "si", "jak", "jednou", "chytil", "na", "hák", "samici", "z",
        "párku", "marlinů", "Samec", "nechává", "samici", "vždycky", "nažrat",
        "první", "a", "chycená", "samice", "se", "pustila", "do", "divokého",
        "zděšeného", "a", "zoufalého", "zápasu", "který", "ji", "brzy",
        "vyčerpal", "a", "samec", "celou", "tu", "dobu", "zůstal", "při", "ní",
        "plul", "přes", "šňůru", "a", "kroužil", "se", "samicí", "na",
        "hladině", "Držel", "se", "tak", "blízko", "že", "se", "starý", "bál",
        "aby", "mu", "nepřeřízl", "šňůru", "svým", "ocasem", "ostrým", "jako",
        "kosa", "a", "téměř", "stejného", "rozměru", "a", "tvaru", "Když", "ji",
        "starý", "přitáhl", "hákovým", "bodcem", "a", "bušil", "do", "ní",
        "kyjem", "drže", "ji", "za", "její", "rapírovitý", "kloun", "s",
        "povrchem", "jako", "ze", "smirkového", "papíru", "bušil", "jí", "do",
        "vršku", "lebky", "až", "změnila", "barvu", "skoro", "do", "odstínu",
        "zadní", "strany", "zrcadel", "a", "když", "ji", "pak", "s",
        "chlapcovou", "pomocí", "vy", "táhl", "do", "člunu", "samec", "zůstal",
        "po", "boku", "loďky", "A", "zatím", "co", "pak", "starý", "uvolňoval",
        "šňůru", "a", "chystal", "si", "harpunu", "samec", "vyskočil", "vedle",
        "člunu", "vysoko", "do", "vzduchu", "aby", "se", "podíval", "kde", "je",
        "samice", "a", "pak", "sjel", "dolů", "do", "hloubky", "s", "široce",
        "roztaženými", "levandulově", "zbarvenými", "křídly", "jimž", "se",
        "podobaly", "jako", "prsní", "ploutve", "a", "vyvstaly", "mu",
        "všechny", "levandulově", "nafialovělé", "pruhy", "Byl", "velice",
        "krásný", "vzpomínal", "si", "stařec", "a", "věrně", "zůstal", "To",
        "byla", "nejsmutnější", "věc", "kterou", "jsem", "s", "nimi", "kdy",
        "zažil", "pomyslel", "si", "stařec", "Chlapec", "byl", "tenkrát",
        "taky", "smutný", "Poprosili", "jsme", "ji", "za", "odpuštění", "a",
        "hned", "jsme", "ji", "vyvrhli", "a", "zpracovali", "Kéž", "by", "teď",
        "chlapec", "byl", "se", "mnou", "řekl", "nahlas", "usadil", "se", "a",
        "opřel", "se", "o", "skruž", "paloubky", "na", "přídi", "a", "cítil",
        "skrze", "šňůru", "sílu", "obrovské", "ryby", "napřenou", "k",
        "neznámému", "cíli", "pro", "který", "se", "ryba", "rozhodla", "Když",
        "už", "se", "následkem", "mého", "úkladu", "nějak", "rozhodnout",
        "musela", "pomyslel", "si", "stařec", "Sama", "by", "se", "bývala",
        "rozhodla", "zůstat", "tam", "dole", "v", "temné", "hloubce", "daleko",
        "mimo", "dosah", "všech", "nástrah", "a", "pastí", "a", "úkladů", "Já",
        "se", "rozhodl", "jít", "za", "ní", "a", "najít", "ji", "mimo", "dosah",
        "všech", "lidí", "Mimo", "dosah", "všech", "lidí", "na", "světě", "Teď",
        "jsme", "spolu", "spojeni", "a", "jsme", "tak", "spojeni", "už", "od",
        "poledne", "A", "nikdo", "nepomůže", "ani", "jednomu", "z", "nás",
        "Snad", "jsem", "se", "neměl", "stát", "rybářem", "pomyslel", "si",
        "Ale", "k", "tomu", "jsem", "se", "narodil", "Určitě", "nesmím",
        "zapomenout", "sníst", "toho", "tuňáka", "až", "začne", "svítat",
        "Někdy", "před", "svítáním", "zabralo", "něco", "najedno", "z",
        "vnadidel", "které", "vláčel", "za", "sebou", "Slyšel", "jak", "praskl",
        "klacek", "a", "šňůra", "se", "začala", "rychle", "odvíjet", "přes",
        "obrubeň", "loďky", "Vytáhl", "v", "temnotě", "z", "pochvy", "nůž",
        "nechal", "si", "všechen", "tah", "ryby", "spočinout", "na", "levém",
        "rameni", "zaklonil", "se", "dozadu", "a", "uřízl", "tu", "šňůru", "na",
        "podložce", "dřevěné", "obrubně", "Pak", "odřízl", "druhou", "šňůru",
        "která", "mu", "byla", "nejblíž", "a", "svázal", "potmě", "volné",
        "konce", "zásobních", "kotoučů", "Pracoval", "obratně", "jednou",
        "rukou", "a", "přišlápl", "kotouče", "nohou", "aby", "je", "přidržel",
        "když", "utahoval", "uzly", "Měl", "teď", "šest", "zásobních",
        "kotoučů", "šňůry", "Dva", "od", "každé", "návnady", "kterou", "odřízl",
        "a", "dva", "od", "návnady", "na", "kterou", "ryba", "zabrala", "a",
        "všechny", "byly", "svázány", "dohromady", "Až", "se", "rozední",
        "myslel", "si", "přelezu", "dozadu", "k", "tomu", "čtyřicetisáhovému",
        "vnadidlu", "uříznu", "je", "taky", "a", "zásobní", "kotouče", "svážu",
        "Přijdu", "tak", "o", "dvě", "stě", "sáhů", "dobrého", "katalánského",
        "cordelu", "o", "háky", "a", "drátěné", "nástavce", "To", "se", "dá",
        "nahradit", "Ale", "kdo", "mi", "nahradí", "tuhle", "rybu", "jestli",
        "chytím", "nějakou", "jinou", "rybu", "a", "ona", "mi", "ji", "odřízne",
        "Nevím", "co", "to", "bylo", "zač", "co", "mi", "teď", "právě",
        "zabralo", "Mohl", "to", "být", "marlin", "nebo", "žralok", "Ani",
        "jsem", "to", "necítil", "Musel", "jsem", "se", "toho", "zbavit", "moc",
        "nahonem", "Nahlas", "řekl", "Kdyby", "tak", "tady", "byl", "chlapec",
        "Ale", "chlapec", "tady", "není", "pomyslel", "si", "Jsi", "tady",
        "jen", "ty", "sám", "a", "měl", "by", "ses", "radši", "dostat", "k",
        "poslední", "šňůře", "hned", "teď", "tma", "netma", "odříznout", "ji",
        "a", "navázat", "zásobní", "kotouče", "A", "taky", "to", "provedl",
        "Bylo", "to", "potmě", "těžké", "a", "ryba", "sebou", "jednou", "trhla",
        "tak", "prudce", "že", "upadl", "na", "obličej", "a", "roztrhl", "si",
        "kůži", "pod", "okem", "Krev", "mu", "stekla", "kousek", "po", "tváři",
        "ale", "srazila", "se", "a", "uschla", "než", "dosáhla", "brady", "a",
        "on", "se", "doplazil", "zpátky", "na", "příď", "a", "odpočíval",
        "opřený", "o", "dřevo", "Narovnal", "si", "pytel", "a", "posunul",
        "opatrně", "šňůru", "tak", "že", "mu", "přišla", "na", "ramenou", "o",
        "kousek", "dál", "a", "když", "si", "ji", "na", "ramenou", "zakotvil",
        "opatrně", "zkusil", "jak", "ryba", "táhne", "a", "pak", "strčil",
        "ruku", "do", "vody", "aby", "cítil", "jak", "loďka", "pluje"

    };
  }

  @Override
  public Collection<String> vratSlova() {
    return Arrays.asList(words);
  }

}
